# Generated by Django 5.1 on 2024-09-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('cro', models.CharField(max_length=20, unique=True, verbose_name='CRO')),
                ('specialty', models.CharField(choices=[('endodontia', 'Endodontia'), ('estomatologia', 'Estomatologia'), ('ortodontia', 'Ortodontia'), ('periodontia', 'Periodontia'), ('odontopediatria', 'Odontopediatria')], max_length=20, verbose_name='Especialidade')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Dentista',
                'verbose_name_plural': 'Dentistas',
            },
        ),
    ]
