# Generated by Django 5.1 on 2024-09-02 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_patient_birth_date_alter_patient_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo')),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data marcada')),
                ('appointment_occasion', models.TextField(verbose_name='Motivo da Consulta')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnóstico')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('concluída', 'Concluída'), ('cancelada', 'Cancelada')], max_length=20, verbose_name='Status')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dentist', verbose_name='Dentista')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient', verbose_name='Paciente')),
                ('procedures_done', models.ManyToManyField(related_name='consultas', to='appointments.procedure', verbose_name='Procedimento(s)')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
